spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 546897f2-ea83-4f86-9649-5de3b449fd34
  main:
    #允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true